export interface Achievement {
  id: string;
  title: string;
  description: string;
  category: 'ranked' | 'league' | 'tournaments' | 'practice' | 'atc' | 'funny' | 'milestones' | 'scoring';
  icon: string;
  completed: boolean;
  progress: number;
  goal: number;
  reward?: string;
  completedDate?: string;
}

export const achievements: Achievement[] = [
  {
    id: 'first-blood',
    title: 'First Blood',
    description: 'Win your first tournament match',
    category: 'tournaments',
    icon: 'trophy',
    completed: true,
    progress: 1,
    goal: 1,
    reward: '100 XP',
    completedDate: '2026-01-15',
  },
  {
    id: 'champion',
    title: 'Champion',
    description: 'Win 1 tournament',
    category: 'tournaments',
    icon: 'trophy',
    completed: true,
    progress: 1,
    goal: 1,
    reward: '250 XP',
    completedDate: '2026-01-16',
  },
  {
    id: 'serial-winner',
    title: 'Serial Winner',
    description: 'Win 5 tournaments',
    category: 'tournaments',
    icon: 'award',
    completed: false,
    progress: 2,
    goal: 5,
    reward: '500 XP',
  },
  {
    id: 'trophy-cabinet',
    title: 'Trophy Cabinet',
    description: 'Win 10 tournaments',
    category: 'tournaments',
    icon: 'trophy',
    completed: false,
    progress: 2,
    goal: 10,
    reward: '1000 XP',
  },
  {
    id: 'elite-champion',
    title: 'Elite Champion',
    description: 'Win 25 tournaments',
    category: 'tournaments',
    icon: 'crown',
    completed: false,
    progress: 2,
    goal: 25,
    reward: '2500 XP',
  },
  {
    id: 'tournament-monster',
    title: 'Tournament Monster',
    description: 'Win 50 tournaments',
    category: 'tournaments',
    icon: 'flame',
    completed: false,
    progress: 2,
    goal: 50,
    reward: '5000 XP',
  },
  {
    id: 'legendary',
    title: 'Legendary',
    description: 'Win 100 tournaments',
    category: 'tournaments',
    icon: 'star',
    completed: false,
    progress: 2,
    goal: 100,
    reward: '10000 XP',
  },
  {
    id: 'bracket-buster',
    title: 'Bracket Buster',
    description: 'Win a tournament without losing a leg',
    category: 'tournaments',
    icon: 'zap',
    completed: false,
    progress: 0,
    goal: 1,
    reward: 'Bracket Buster Badge',
  },
  {
    id: 'final-boss',
    title: 'Final Boss',
    description: 'Win a tournament final from behind',
    category: 'tournaments',
    icon: 'target',
    completed: false,
    progress: 0,
    goal: 1,
    reward: '750 XP',
  },
  {
    id: 'weekend-warrior',
    title: 'Weekend Warrior',
    description: 'Win a weekend tournament',
    category: 'tournaments',
    icon: 'calendar',
    completed: false,
    progress: 0,
    goal: 1,
    reward: '300 XP',
  },
  {
    id: 'joined-ranks',
    title: 'Joined the Ranks',
    description: 'Join your first league',
    category: 'league',
    icon: 'users',
    completed: false,
    progress: 0,
    goal: 1,
    reward: '100 XP',
  },
  {
    id: 'league-winner',
    title: 'League Winner',
    description: 'Win 1 league title',
    category: 'league',
    icon: 'trophy',
    completed: false,
    progress: 0,
    goal: 1,
    reward: '500 XP',
  },
  {
    id: 'dominant-season',
    title: 'Dominant Season',
    description: 'Win 5 league titles',
    category: 'league',
    icon: 'award',
    completed: false,
    progress: 0,
    goal: 5,
    reward: '2000 XP',
  },
  {
    id: 'dynasty',
    title: 'Dynasty',
    description: 'Win 10 league titles',
    category: 'league',
    icon: 'crown',
    completed: false,
    progress: 0,
    goal: 10,
    reward: '5000 XP',
  },
  {
    id: 'immortal',
    title: 'Immortal',
    description: 'Win 25 league titles',
    category: 'league',
    icon: 'star',
    completed: false,
    progress: 0,
    goal: 25,
    reward: 'Immortal Badge',
  },
  {
    id: 'the-gaffer',
    title: 'The Gaffer',
    description: 'Create a league',
    category: 'league',
    icon: 'plus-circle',
    completed: false,
    progress: 0,
    goal: 1,
    reward: '200 XP',
  },
  {
    id: 'invincible-season',
    title: 'Invincible Season',
    description: 'Finish a league unbeaten',
    category: 'league',
    icon: 'shield',
    completed: false,
    progress: 0,
    goal: 1,
    reward: 'Invincible Badge',
  },
  {
    id: 'great-escape',
    title: 'Great Escape',
    description: 'Avoid relegation on the final match',
    category: 'league',
    icon: 'heart',
    completed: false,
    progress: 0,
    goal: 1,
    reward: '250 XP',
  },
  {
    id: 'promotion-party',
    title: 'Promotion Party',
    description: 'Earn promotion',
    category: 'league',
    icon: 'trending-up',
    completed: false,
    progress: 0,
    goal: 1,
    reward: '400 XP',
  },
  {
    id: 'relegation-tears',
    title: 'Relegation Tears',
    description: 'Get relegated twice',
    category: 'funny',
    icon: 'frown',
    completed: false,
    progress: 0,
    goal: 2,
    reward: 'Pain Badge',
  },
  {
    id: 'boom',
    title: 'Boom!',
    description: 'Hit your first 180',
    category: 'scoring',
    icon: 'target',
    completed: true,
    progress: 1,
    goal: 1,
    reward: '150 XP',
    completedDate: '2026-01-10',
  },
  {
    id: 'maximum-effort',
    title: 'Maximum Effort',
    description: 'Hit 5x 180s',
    category: 'scoring',
    icon: 'zap',
    completed: false,
    progress: 3,
    goal: 5,
    reward: '300 XP',
  },
  {
    id: 'ton-80-club',
    title: 'The Ton 80 Club',
    description: 'Hit 10x 180s',
    category: 'scoring',
    icon: 'star',
    completed: false,
    progress: 3,
    goal: 10,
    reward: '600 XP',
  },
  {
    id: 'treble-trouble',
    title: 'Treble Trouble',
    description: 'Hit 25x 180s',
    category: 'scoring',
    icon: 'flame',
    completed: false,
    progress: 3,
    goal: 25,
    reward: '1500 XP',
  },
  {
    id: '180-machine',
    title: '180 Machine',
    description: 'Hit 50x 180s',
    category: 'scoring',
    icon: 'cpu',
    completed: false,
    progress: 3,
    goal: 50,
    reward: '3000 XP',
  },
  {
    id: 'maximum-overload',
    title: 'Maximum Overload',
    description: 'Hit 100x 180s',
    category: 'scoring',
    icon: 'rocket',
    completed: false,
    progress: 3,
    goal: 100,
    reward: '6000 XP',
  },
  {
    id: 'treble-factory',
    title: 'Treble Factory',
    description: 'Hit 250x 180s',
    category: 'scoring',
    icon: 'factory',
    completed: false,
    progress: 3,
    goal: 250,
    reward: '15000 XP',
  },
  {
    id: 'treble-god',
    title: 'Treble God',
    description: 'Hit 500x 180s',
    category: 'scoring',
    icon: 'crown',
    completed: false,
    progress: 3,
    goal: 500,
    reward: 'Treble God Badge',
  },
  {
    id: 'back-to-back',
    title: 'Back-to-Back',
    description: 'Hit 2 consecutive 180s in one match',
    category: 'scoring',
    icon: 'repeat',
    completed: false,
    progress: 0,
    goal: 1,
    reward: '500 XP',
  },
  {
    id: '180-under-pressure',
    title: '180 Under Pressure',
    description: 'Hit a 180 to win a deciding leg',
    category: 'scoring',
    icon: 'crosshair',
    completed: false,
    progress: 0,
    goal: 1,
    reward: 'Clutch Badge',
  },
  {
    id: 'checked-out',
    title: 'Checked Out',
    description: 'Win a leg by checkout',
    category: 'scoring',
    icon: 'check',
    completed: true,
    progress: 1,
    goal: 1,
    reward: '50 XP',
    completedDate: '2026-01-08',
  },
  {
    id: 'cool-hand',
    title: 'Cool Hand',
    description: 'Checkout above 100',
    category: 'scoring',
    icon: 'circle-dot',
    completed: false,
    progress: 0,
    goal: 1,
    reward: '200 XP',
  },
  {
    id: 'big-finish',
    title: 'Big Finish',
    description: 'Checkout above 120',
    category: 'scoring',
    icon: 'target',
    completed: false,
    progress: 0,
    goal: 1,
    reward: '300 XP',
  },
  {
    id: 'clutch-finisher',
    title: 'Clutch Finisher',
    description: 'Checkout above 150',
    category: 'scoring',
    icon: 'zap',
    completed: false,
    progress: 0,
    goal: 1,
    reward: '500 XP',
  },
  {
    id: 'out-in-style',
    title: 'Out in Style',
    description: 'Checkout with bull',
    category: 'scoring',
    icon: 'disc',
    completed: false,
    progress: 0,
    goal: 1,
    reward: '250 XP',
  },
  {
    id: 'double-trouble',
    title: 'Double Trouble',
    description: 'Miss 5 doubles in a row',
    category: 'funny',
    icon: 'x-circle',
    completed: false,
    progress: 2,
    goal: 5,
    reward: 'Unlucky Badge',
  },
  {
    id: 'ice-cold',
    title: 'Ice Cold',
    description: 'Checkout on first dart at double',
    category: 'scoring',
    icon: 'snowflake',
    completed: false,
    progress: 0,
    goal: 1,
    reward: '400 XP',
  },
  {
    id: 'shanghai-surprise',
    title: 'Shanghai Surprise',
    description: 'Hit a Shanghai finish',
    category: 'scoring',
    icon: 'sparkles',
    completed: false,
    progress: 0,
    goal: 1,
    reward: 'Shanghai Badge',
  },
  {
    id: '170-club',
    title: '170 Club',
    description: 'Checkout 170',
    category: 'scoring',
    icon: 'award',
    completed: false,
    progress: 0,
    goal: 1,
    reward: '1000 XP',
  },
  {
    id: 'ton-up',
    title: 'Ton Up',
    description: 'Hit 100+',
    category: 'scoring',
    icon: 'arrow-up',
    completed: true,
    progress: 1,
    goal: 1,
    reward: '100 XP',
    completedDate: '2026-01-12',
  },
  {
    id: 'ton-machine',
    title: 'Ton Machine',
    description: 'Hit 10x 100+',
    category: 'scoring',
    icon: 'repeat',
    completed: false,
    progress: 4,
    goal: 10,
    reward: '300 XP',
  },
  {
    id: 'heavy-scorer',
    title: 'Heavy Scorer',
    description: 'Average 60+ in a match',
    category: 'milestones',
    icon: 'trending-up',
    completed: false,
    progress: 0,
    goal: 1,
    reward: '200 XP',
  },
  {
    id: 'serious-business',
    title: 'Serious Business',
    description: 'Average 80+ in a match',
    category: 'milestones',
    icon: 'bar-chart',
    completed: false,
    progress: 0,
    goal: 1,
    reward: '400 XP',
  },
  {
    id: 'centurion',
    title: 'Centurion',
    description: 'Average 100+ in a match',
    category: 'milestones',
    icon: 'trophy',
    completed: false,
    progress: 0,
    goal: 1,
    reward: 'Centurion Badge',
  },
  {
    id: 'the-wall',
    title: 'The Wall',
    description: 'Win a match without dropping a leg',
    category: 'milestones',
    icon: 'shield',
    completed: false,
    progress: 0,
    goal: 1,
    reward: '300 XP',
  },
  {
    id: 'early-doors',
    title: 'Early Doors',
    description: 'Win a match in under 10 minutes',
    category: 'milestones',
    icon: 'clock',
    completed: false,
    progress: 0,
    goal: 1,
    reward: '250 XP',
  },
  {
    id: 'feared-number',
    title: 'The Feared Number',
    description: 'Score 26 for the first time',
    category: 'funny',
    icon: 'alert-triangle',
    completed: true,
    progress: 1,
    goal: 1,
    reward: '10 XP',
    completedDate: '2026-01-09',
  },
  {
    id: 'double-13-specialist',
    title: 'Double 13 Specialist',
    description: 'Score 26 ten times',
    category: 'funny',
    icon: 'frown',
    completed: false,
    progress: 5,
    goal: 10,
    reward: 'Pain Badge',
  },
  {
    id: 'pain-merchant',
    title: 'Pain Merchant',
    description: 'Score 26 fifty times',
    category: 'funny',
    icon: 'skull',
    completed: false,
    progress: 5,
    goal: 50,
    reward: 'Suffering Badge',
  },
  {
    id: 'anti-checkout',
    title: 'Anti-Checkout',
    description: 'Score 26 one hundred times',
    category: 'funny',
    icon: 'x',
    completed: false,
    progress: 5,
    goal: 100,
    reward: 'Masochist Badge',
  },
  {
    id: 'dartboard-hates-me',
    title: 'Dartboard Hates Me',
    description: 'Score 26 three times in one match',
    category: 'funny',
    icon: 'angry',
    completed: false,
    progress: 0,
    goal: 1,
    reward: 'Unlucky Badge',
  },
  {
    id: 'ranked-rookie',
    title: 'Ranked Rookie',
    description: 'Play your first ranked match',
    category: 'ranked',
    icon: 'play',
    completed: false,
    progress: 0,
    goal: 1,
    reward: '100 XP',
  },
  {
    id: 'on-the-ladder',
    title: 'On The Ladder',
    description: 'Win 5 ranked matches',
    category: 'ranked',
    icon: 'trending-up',
    completed: false,
    progress: 0,
    goal: 5,
    reward: '250 XP',
  },
  {
    id: 'ranked-grinder',
    title: 'Ranked Grinder',
    description: 'Win 25 ranked matches',
    category: 'ranked',
    icon: 'award',
    completed: false,
    progress: 0,
    goal: 25,
    reward: '1000 XP',
  },
  {
    id: 'sweaty-hands',
    title: 'Sweaty Hands',
    description: 'Win 50 ranked matches',
    category: 'ranked',
    icon: 'droplet',
    completed: false,
    progress: 0,
    goal: 50,
    reward: '2000 XP',
  },
  {
    id: 'the-tryhard',
    title: 'The Tryhard',
    description: 'Win 100 ranked matches',
    category: 'funny',
    icon: 'flame',
    completed: false,
    progress: 0,
    goal: 100,
    reward: 'Tryhard Badge',
  },
  {
    id: 'win-streak',
    title: 'Win Streak',
    description: 'Win 5 ranked matches in a row',
    category: 'ranked',
    icon: 'zap',
    completed: false,
    progress: 0,
    goal: 5,
    reward: '500 XP',
  },
  {
    id: 'unstoppable',
    title: 'Unstoppable',
    description: 'Win 10 ranked matches in a row',
    category: 'ranked',
    icon: 'rocket',
    completed: false,
    progress: 0,
    goal: 10,
    reward: 'Unstoppable Badge',
  },
  {
    id: 'revenge-arc',
    title: 'Revenge Arc',
    description: 'Beat a player who beat you last time',
    category: 'ranked',
    icon: 'rotate-ccw',
    completed: false,
    progress: 0,
    goal: 1,
    reward: '300 XP',
  },
  {
    id: 'promotion-secured',
    title: 'Promotion Secured',
    description: 'Reach a new division',
    category: 'ranked',
    icon: 'chevrons-up',
    completed: false,
    progress: 0,
    goal: 1,
    reward: '400 XP',
  },
  {
    id: 'friendly-fire',
    title: 'Friendly Fire',
    description: 'Play a private match',
    category: 'milestones',
    icon: 'users',
    completed: false,
    progress: 0,
    goal: 1,
    reward: '50 XP',
  },
  {
    id: 'rivalry',
    title: 'Rivalry',
    description: 'Play the same opponent 10 times',
    category: 'milestones',
    icon: 'swords',
    completed: false,
    progress: 0,
    goal: 10,
    reward: '500 XP',
  },
  {
    id: 'best-frenemies',
    title: 'Best Frenemies',
    description: 'Beat your friend 25 times',
    category: 'funny',
    icon: 'laugh',
    completed: false,
    progress: 0,
    goal: 25,
    reward: 'Frenemy Badge',
  },
  {
    id: 'group-chat-hero',
    title: 'Group Chat Hero',
    description: 'Win a match after trash talk',
    category: 'funny',
    icon: 'message-circle',
    completed: false,
    progress: 0,
    goal: 1,
    reward: '200 XP',
  },
  {
    id: 'warm-up',
    title: 'Warm Up',
    description: 'Complete 10 practice sessions',
    category: 'practice',
    icon: 'activity',
    completed: false,
    progress: 0,
    goal: 10,
    reward: '150 XP',
  },
  {
    id: 'dedicated',
    title: 'Dedicated',
    description: 'Practice 50 times',
    category: 'practice',
    icon: 'target',
    completed: false,
    progress: 0,
    goal: 50,
    reward: '500 XP',
  },
  {
    id: 'training-arc',
    title: 'Training Arc',
    description: 'Practice 100 times',
    category: 'practice',
    icon: 'dumbbell',
    completed: false,
    progress: 0,
    goal: 100,
    reward: 'Dedicated Badge',
  },
  {
    id: 'bullseye-hunter',
    title: 'Bullseye Hunter',
    description: 'Hit 25 bulls in practice',
    category: 'practice',
    icon: 'circle-dot',
    completed: false,
    progress: 0,
    goal: 25,
    reward: '400 XP',
  },
  {
    id: 'robin-hood',
    title: 'Robin Hood',
    description: 'Hit the same treble 3 darts in a row',
    category: 'practice',
    icon: 'target',
    completed: false,
    progress: 0,
    goal: 1,
    reward: 'Robin Hood Badge',
  },
  {
    id: 'clock-starter',
    title: 'Clock Starter',
    description: 'Complete Around The Clock once',
    category: 'atc',
    icon: 'clock',
    completed: false,
    progress: 0,
    goal: 1,
    reward: '100 XP',
  },
  {
    id: 'clock-master',
    title: 'Clock Master',
    description: 'Complete 10 times',
    category: 'atc',
    icon: 'timer',
    completed: false,
    progress: 0,
    goal: 10,
    reward: '500 XP',
  },
  {
    id: 'clock-legend',
    title: 'Clock Legend',
    description: 'Complete 50 times',
    category: 'atc',
    icon: 'award',
    completed: false,
    progress: 0,
    goal: 50,
    reward: 'Clock Legend Badge',
  },
  {
    id: 'speed-runner',
    title: 'Speed Runner',
    description: 'Complete Around The Clock under 5 minutes',
    category: 'atc',
    icon: 'zap',
    completed: false,
    progress: 0,
    goal: 1,
    reward: '750 XP',
  },
  {
    id: 'missed-20-times',
    title: 'Missed 20 Times',
    description: 'Miss the same number 20 times',
    category: 'funny',
    icon: 'frown',
    completed: false,
    progress: 0,
    goal: 20,
    reward: 'Persistence Badge',
  },
  {
    id: 'pub-thrower',
    title: 'The Pub Thrower',
    description: 'Win a match with a lower average than your opponent',
    category: 'funny',
    icon: 'beer',
    completed: false,
    progress: 0,
    goal: 1,
    reward: 'Pub Legend Badge',
  },
  {
    id: 'bottle-job',
    title: 'The Bottle Job',
    description: 'Lose a match from 1 dart away',
    category: 'funny',
    icon: 'alert-circle',
    completed: false,
    progress: 0,
    goal: 1,
    reward: 'Bottler Badge',
  },
  {
    id: 'dartboard-bully',
    title: 'Dartboard Bully',
    description: 'Hit 20 twenty times in a row',
    category: 'milestones',
    icon: 'target',
    completed: false,
    progress: 0,
    goal: 20,
    reward: '800 XP',
  },
  {
    id: 'wall-inspector',
    title: 'The Wall Inspector',
    description: 'Miss the board 10 times in 1 game',
    category: 'funny',
    icon: 'home',
    completed: false,
    progress: 0,
    goal: 10,
    reward: 'Inspector Badge',
  },
  {
    id: 'respectfully',
    title: 'Respectfully',
    description: 'Win then immediately rematch 5 times',
    category: 'funny',
    icon: 'handshake',
    completed: false,
    progress: 0,
    goal: 5,
    reward: 'Respectful Badge',
  },
  {
    id: 'nice',
    title: 'Nice.',
    description: 'Score exactly 69 in a single visit.',
    category: 'funny',
    icon: 'smile',
    completed: false,
    progress: 0,
    goal: 1,
    reward: '69 XP',
  },
];

export function getCategoryName(category: Achievement['category']): string {
  const names = {
    ranked: 'Ranked',
    league: 'League',
    tournaments: 'Tournaments',
    practice: 'Practice',
    atc: 'Around The Clock',
    funny: 'Funny',
    milestones: 'Milestones',
    scoring: 'Scoring',
  };
  return names[category];
}

export function getAchievementStats(achievementsList: Achievement[] = achievements) {
  const completed = achievementsList.filter((a) => a.completed).length;
  const total = achievementsList.length;
  const percentage = Math.round((completed / total) * 100);
  return { completed, total, percentage };
}

export function mergeUserAchievements(
  staticAchievements: Achievement[],
  userAchievements: Array<{ achievement_id: string; completed: boolean; progress: number; completed_at: string | null }>
): Achievement[] {
  return staticAchievements.map(achievement => {
    const userAchievement = userAchievements.find(ua => ua.achievement_id === achievement.id);

    if (userAchievement) {
      return {
        ...achievement,
        completed: userAchievement.completed,
        progress: userAchievement.progress,
        completedDate: userAchievement.completed_at ? new Date(userAchievement.completed_at).toISOString().split('T')[0] : undefined,
      };
    }

    return {
      ...achievement,
      completed: false,
      progress: 0,
      completedDate: undefined,
    };
  });
}

export function mapDbAchievementToFrontend(dbAchievement: any): Achievement {
  const categoryMap: Record<string, Achievement['category']> = {
    'General': 'milestones',
    'Funny': 'funny',
    'Scoring': 'scoring',
    'Finishing': 'scoring',
    'Streaks': 'milestones',
    'Competitive': 'ranked',
  };

  return {
    id: dbAchievement.code,
    title: dbAchievement.name,
    description: dbAchievement.description,
    category: categoryMap[dbAchievement.category] || 'milestones',
    icon: dbAchievement.icon,
    completed: false,
    progress: 0,
    goal: dbAchievement.goal_value || 1,
    reward: `${dbAchievement.xp} XP`,
  };
}
