/*
  # Fix Quick Match Notification Links

  Update the notification link in the quick match RPC function to use the correct route.

  ## Changes
  - Update `join_quick_match_lobby` function to use `/play/quick-match/match/` instead of `/quick-match/match/`
  - This ensures any future notifications generated by this RPC use the correct route

  ## Notes
  - The RPC function is currently not used by the application but this ensures consistency
  - The main lobby page handles joins directly without using this RPC
*/

-- Drop and recreate the function with the correct notification link
CREATE OR REPLACE FUNCTION join_quick_match_lobby(lobby_uuid uuid)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_lobby quick_match_lobbies;
  v_match_id uuid;
  v_user_id uuid;
BEGIN
  -- Get current user
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'User must be authenticated';
  END IF;

  -- Get lobby
  SELECT * INTO v_lobby FROM quick_match_lobbies WHERE id = lobby_uuid FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Lobby not found';
  END IF;

  IF v_lobby.status != 'open' THEN
    RAISE EXCEPTION 'Lobby is not open';
  END IF;

  IF v_lobby.player2_id IS NOT NULL THEN
    RAISE EXCEPTION 'Lobby already has a second player';
  END IF;

  IF v_lobby.player1_id = v_user_id THEN
    RAISE EXCEPTION 'Cannot join your own lobby';
  END IF;

  -- Create match
  INSERT INTO online_matches (
    lobby_id,
    player1_id,
    player2_id,
    game_type,
    format,
    double_out,
    current_player_id,
    p1_remaining,
    p2_remaining,
    p1_legs_won,
    p2_legs_won,
    leg_number,
    status
  ) VALUES (
    lobby_uuid,
    v_lobby.player1_id,
    v_user_id,
    v_lobby.game_type,
    v_lobby.format,
    v_lobby.double_out,
    v_lobby.player1_id,
    v_lobby.game_type,
    v_lobby.game_type,
    0,
    0,
    1,
    'active'
  ) RETURNING id INTO v_match_id;

  -- Update lobby
  UPDATE quick_match_lobbies
  SET
    player2_id = v_user_id,
    match_id = v_match_id,
    status = 'matched'
  WHERE id = lobby_uuid;

  -- Send notification to host with correct link
  INSERT INTO notifications (user_id, type, title, message, link, read)
  VALUES (
    v_lobby.player1_id,
    'quick_match_ready',
    'Match Ready!',
    'Your opponent has joined',
    '/play/quick-match/match/' || v_match_id,
    false
  );

  RETURN v_match_id;
END;
$$;